### ISSUE TITLE
Skill System - TODO

### ISSUE THREAD

**Issue by cafne** [cafne/DMBot#2]
- Core Components
  - [x] Integration with stats
  - [x] Intergration with buffs
  - [x] Integration with dice roller
  - [x] Support for targeting 
- [x] JSON parser
- [x] Multiskill usage
This would allow for multiple rolls per command. For example: `!attack`
  Normally: 
  >1.<Player 1> uses `!hit <Player 2>` to check DEX
  >2. If <Player 1> rolls higher than <Player 2>, <Player 1> uses `!attack <Player 2>`
  
  With Multiskills, this can be simplified down to a single `!attack <Player 2>` command.
- "Use" command
  - [x] Integration with stats and rolls
  - [x] Support for applying new buffs on use
