### ISSUE TITLE
Item System - TODO

### ISSUE THREAD

**Issue by cafne** [cafne/DMBot#3]
- [x] Core Components 
- "New" command
  - [x] Create Base Item
  - [x] Support for channel unlocking
  - [ ] Support for buffs
- [ ] "Remove" Command
- [ ] Intergration with player Inventory
- [ ] JSON Parser
- [ ] Embed Function
