### ISSUE TITLE
Buff System - TODO

### ISSUE THREAD

**Issue by cafne** [cafne/DMBot#4]
- [x] Core Components
- [x] Support for stacking
- [x] "New" command (!newbuff)
- "Use" command
  - [x] Use predefined buff/debuff
  - [x] Add a regular modifier
- [x] JSON parser
- [x] "Remove" Command
- [x] Embed Function
